name: 'Extract PR comment'
description: 'GitHub action to get PR comment URL'
author: 'Patryk Tomczyk @patzick'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 500
runs:
  using: 'node12'
  main: 'dist/index.js'