name: 'Extract PR comment'
description: 'GitHub action to get PR comment URL'
author: 'Patryk Tomczyk @patzick'
inputs:
  token:
    description: 'Github API token'
    required: true
  patterns:
    description: 'List of patterns you have in comments with URLs'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'