name: "Test Comment Action"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  
  extract-comment:
    runs-on: ubuntu-latest
    steps:
    - uses: patzick/action-get-comment-url@main
      with:
        gitToken: ${{ secrets.GITHUB_TOKEN }}
        patterns: |
          my comment pattern