name: "Test Comment Action"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  
  extract-comment:
    runs-on: ubuntu-latest
    steps:
    - uses: patzick/action-get-comment-url@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pattern: |
          shopware-pwa-canary successfully deployed
          another pattern?